mode: quantized_emb
sample_rate: 24000
probe_ckpt_path: /sdb/tmp/user/wzy/codec_eval/ctc_libritts/ckpt/dac_quantized_emb_epoch=3-val_loss=2.8987.ckpt
seed: 666
codec_name: dac
save_asr_result: null # /sdb/tmp/user/wzy/codec_eval/ctc_libritts/result/dac_asr.jsonl

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: [1]
  precision: 32
  deterministic: true  # ensure reproducible results
  enable_progress_bar: true  # show progress bar
  enable_checkpointing: false  # no need to save checkpoints during testing
  # limit_test_batches: 5  # only test 5 samples for debugging

data:
  _target_: codec_evaluation.probe.dataset.LibriTTS_dataset.libritts_ctc.LibriTTS_ctc_module
  train_audio_dir: /sdb/data1/speech/24kHz/LibriTTS/train-clean-100
  valid_audio_dir: /sdb/data1/speech/24kHz/LibriTTS/dev-other
  test_audio_dir: /sdb/data1/speech/24kHz/LibriTTS/test-clean
  test_batch_size: 32
  test_num_workers: 4

model:
  _target_: codec_evaluation.probe.model.ctc_lit_prober.CtcLitProber
  codec_name: ${codec_name}
  sample_rate: ${sample_rate}
  mode: ${mode}
  probe_model_builder:
    _target_: codec_evaluation.probe.model.LibriTTS_dataset.model.Ctc_probe_model
    _partial_: true
    tokenizer:
      _target_: transformers.Speech2TextProcessor.from_pretrained
      pretrained_model_name_or_path: /sdb/model_weight/s2t-small-librispeech-asr
    vocab_size: 10000
    dropout: 0.1
    conformer_head: 8
  model_ckpt_dir: /sdb/model_weight/codec_evaluation/codec_ckpt/

  optimizer_builder:
      _target_: torch.optim.AdamW
      _partial_: true
      lr: 1e-4
      betas: [0.8, 0.99]
      eps: 1e-5
      weight_decay: 0.08
    
  lr_scheduler_builder:
    _target_: torch.optim.lr_scheduler.LambdaLR
    _partial_: true
    lr_lambda:
      _target_: codec_evaluation.utils.schedule.get_cosine_schedule_with_warmup_lr_lambda
      _partial_: true
      num_warmup_steps: 200
      num_training_steps: 4000
      final_lr_ratio: 0.2

callbacks:
  learning_rate_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step

  rich_progress_bar:
    _target_: pytorch_lightning.callbacks.RichProgressBar

  model_summary:
    _target_: pytorch_lightning.callbacks.ModelSummary
    max_depth: 1