_import:
  - !include benchmark/tasks/GTZAN/GTZAN_base_config.yaml

dataset:
  pre_extract:
    accelerator: gpu
    audio_dir: data/GTZAN/genres
    output_dir: data/GTZAN/hubert_features/hubert-base-ls960_feature_default
    keep_folder_structure: true
    overwrite: true

    audio_loader:
      is_mono: true
      is_normalize: false  # min-max normalization
      crop_to_length_in_sec: null
      crop_to_length_in_sample_points: null
      crop_randomly: false
      sliding_window_size_in_sec: 30.0
      sliding_window_overlap_in_percent: 0.0

    feature_extractor:
      pretrain:
        !include benchmark/models/hubert/hubert-base-ls960.yaml
      force_half: false
      layer: null # null means save features from all layers
      reduction: mean # [mean, max, min, none]
  dataset: GTZAN
  input_type: feature # [audio, feature]
  input_dir: data/GTZAN/hubert_features/hubert-base-ls960_feature_default
  metadata_dir: data/GTZAN

model:    
    downstream_structure:
      components:
        - name: feature_selector
          layer: 0 # not a transformer model, so layer is set to 0
        - name: mlp
          hidden_layer_sizes: [512]
          dropout_p: 0.2
          num_outputs: 10
  