_import:
  - !include benchmark/tasks/GS/GS_base_config.yaml

dataset:
  pre_extract:
    accelerator: gpu
    audio_dir: data/GS/giantsteps_clips/wav
    output_dir: data/GS/musicnn_features/musicnn_feature_default
    keep_folder_structure: true
    overwrite: true

    feature_extractor:
      pretrain:
        !include benchmark/models/musicnn/musicnn.yaml

  dataset: GS
  input_type: feature # [audio, feature]
  input_dir: data/GS/musicnn_features/musicnn_feature_default
  metadata_dir: data/GS/giantsteps_clips

model:    
    downstream_structure:
      components:
        - name: feature_selector
          layer: 0 # not a transformer model, so layer is set to 0
        - name: mlp
          hidden_layer_sizes: [512]
          dropout_p: 0.2
          num_outputs: 10
  