# Path: benchmark/tasks/GTZAN/GTZANBT_base_config.yaml
# Description: 
#   Base config for GTZAN. It show case the usage of probing MERT-v1-95M model on GTZAN dataset.

dataset:
  audio_loader:
    is_mono: true
    is_normalize: false  # min-max normalization
    crop_to_length_in_sec: 
      train: 10.0
      valid: 30.0
      test: 30.0
    crop_randomly:
      train: true
      valid: false
      test: false
    pad:
      train: false
      valid: true
      test: true
    return_start:
      train: true
      valid: false
      test: false
    

  dataset: GTZANBT
  input_type: audio # [audio, feature]
  input_dir: data/GTZAN/genres
  metadata_dir: data/GTZAN/GTZAN-Rhythm_v2_ismir2015_lbd/jams

model:    
  feature_extractor:
    pretrain:
      !include benchmark/models/musichubert_hf/MERT-v1-95M.yaml
    force_half: false
    reduction: none # [mean, max, min, none]

  downstream_structure:
    components:
      - name: feature_selector
        layer: all # [all, 0, 1, 2, ..., $n_tranformer_layer]
        # weighted sum is only effective when layer is set to all
        normalized_weight_sum: true

      - name: mlp
        hidden_layer_sizes: [512]
        dropout_p: 0.2
        num_outputs: 2


trainer: 
  # pytorch lightning trainer args
  auto_lr_find: false
  accelerator: gpu
  devices: 1
  strategy: null # [null, ddp]
  precision: 16
  accumulate_grad_batches: 1
  fast_dev_run: false
  log_every_n_steps: 50
  max_epochs: 100 

  # custom args
  seed: 1234
  eval_only: false
  paradigm: probe # [probe, finetune]


dataloader:
  num_workers: 0
  batch_size:
    train: 1
    valid: 1
    test: 1


optimizer:
  name: torch.optim.Adam
  l2_weight_decay: 0.0
  lr: 1e-3


scheduler:
  lr_scheduler_patience: 6
  earlystop_patience: 20


loss:
  loss_weight: null


logger:
  wandb_off: false # turn off wandb
  wandb_proj_name: Eval_GTZAN_probing
  wandb_run_name: null
  wandb_dir: data
  wandb_sweep: false
  monitor: valid_beat_f


checkpoint:
  save_best_to: null
  eval_ckpt_path: null


hp_search:
  enable: false
  framework: ray
  technique: grid_search # [grid_search, random_search, bayesian_optimization, hyperband, asha]
  search_list: 
    - name: lr
      space: [1e-2, 5e-3, 1e-3, 5e-4, 1e-4]

